/* Main Simulation File */
/* Simulation code for plant generated by the OpenModelica Compiler 1.9.2+dev (r23940). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "plant_functions.h"
#include "plant_model.h"
#include "plant_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#define prefixedName_performSimulation plant_performSimulation
#include <simulation/solver/perform_simulation.c>

/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = omc_dummyFileInfo;
const VAR_INFO dummyVAR_INFO = omc_dummyVarInfo;
#if defined(__cplusplus)
extern "C" {
#endif
int measure_time_flag = 0;

int plant_input_function(DATA *data)
{
  return 0;
}

int plant_input_function_init(DATA *data)
{
  return 0;
}

int plant_output_function(DATA *data)
{
  return 0;
}


/*
 equation index: 5
 type: SIMPLE_ASSIGN
 der(ageep._z) = ageep.myv.x
 */
void plant_eqFunction_5(DATA *data)
{
  const int equationIndexes[2] = {1,5};
  TRACE_PUSH
  $P$DER$Pageep$Pz = $Pageep$Pmyv$Px;
  TRACE_POP
}
/*
 equation index: 6
 type: SIMPLE_ASSIGN
 der(ageep._myv._x) = ageep.myv.speed
 */
void plant_eqFunction_6(DATA *data)
{
  const int equationIndexes[2] = {1,6};
  TRACE_PUSH
  $P$DER$Pageep$Pmyv$Px = $Pageep$Pmyv$Pspeed;
  TRACE_POP
}


int plant_functionDAE(DATA *data)
{
  int equationIndexes[1] = {0};
  
  TRACE_PUSH
  
  data->simulationInfo.needToIterate = 0;
  data->simulationInfo.discreteCall = 1;
  plant_eqFunction_5(data);

  plant_eqFunction_6(data);
  
  TRACE_POP
  return 0;
}


/* forwarded equations */
extern void plant_eqFunction_5(DATA* data);
extern void plant_eqFunction_6(DATA* data);

static void functionODE_system0(DATA *data)
{
  plant_eqFunction_5(data);

  plant_eqFunction_6(data);
}

int plant_functionODE(DATA *data)
{

  
  TRACE_PUSH
  data->simulationInfo.callStatistics.functionODE++;
  
  data->simulationInfo.discreteCall = 0;
  functionODE_system0(data);

  
  TRACE_POP
  return 0;
}

/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data);

#include "plant_12jac.h"
#include "plant_13opt.h"
extern void plant_callExternalObjectConstructors(DATA *data);
extern void plant_callExternalObjectDestructors(DATA *_data);
extern void plant_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
extern void plant_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
extern void plant_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA *data);
extern void plant_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
extern int plant_functionAlgebraics(DATA *data);
extern int plant_function_storeDelayed(DATA *data);
extern int plant_updateBoundVariableAttributes(DATA *data);
extern const char* plant_initialResidualDescription(int);
extern int plant_initial_residual(DATA *data, double* initialResiduals);
extern int plant_functionInitialEquations(DATA *data);
extern int plant_functionRemovedInitialEquations(DATA *data);
extern int plant_updateBoundParameters(DATA *data);
extern int plant_checkForAsserts(DATA *data);
extern int plant_function_ZeroCrossingsEquations(DATA *data);
extern int plant_function_ZeroCrossings(DATA *data, double* gout);
extern int plant_function_updateRelations(DATA *data, int evalZeroCross);
extern int plant_checkForDiscreteChanges(DATA *data);
extern const char* plant_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* plant_relationDescription(int i);
extern void plant_function_initSample(DATA *data);
extern int plant_initialAnalyticJacobianG(void* data);
extern int plant_initialAnalyticJacobianA(void* data);
extern int plant_initialAnalyticJacobianB(void* data);
extern int plant_initialAnalyticJacobianC(void* data);
extern int plant_initialAnalyticJacobianD(void* data);
extern int plant_functionJacG_column(void* data);
extern int plant_functionJacA_column(void* data);
extern int plant_functionJacB_column(void* data);
extern int plant_functionJacC_column(void* data);
extern int plant_functionJacD_column(void* data);
extern const char* plant_linear_model_frame(void);
extern int plant_mayer(DATA* data, modelica_real** res, short *);
extern int plant_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int plant_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);

struct OpenModelicaGeneratedFunctionCallbacks plant_callback = {
   (int (*)(DATA *, void *)) plant_performSimulation,
   plant_callExternalObjectConstructors,
   plant_callExternalObjectDestructors,
   plant_initialNonLinearSystem,
   plant_initialLinearSystem,
   plant_initialMixedSystem,
   plant_initializeStateSets,
   plant_functionODE,
   plant_functionAlgebraics,
   plant_functionDAE,
   plant_input_function,
   plant_input_function_init,
   plant_output_function,
   plant_function_storeDelayed,
   plant_updateBoundVariableAttributes,
   plant_initialResidualDescription,
   plant_initial_residual,
   1 /* useSymbolicInitialization */,
   0 /* useHomotopy */,
   plant_functionInitialEquations,
   plant_functionRemovedInitialEquations,
   plant_updateBoundParameters,
   plant_checkForAsserts,
   plant_function_ZeroCrossingsEquations,
   plant_function_ZeroCrossings,
   plant_function_updateRelations,
   plant_checkForDiscreteChanges,
   plant_zeroCrossingDescription,
   plant_relationDescription,
   plant_function_initSample,
   plant_INDEX_JAC_A,
   plant_INDEX_JAC_B,
   plant_INDEX_JAC_C,
   plant_INDEX_JAC_D,
   plant_initialAnalyticJacobianA,
   plant_initialAnalyticJacobianB,
   plant_initialAnalyticJacobianC,
   plant_initialAnalyticJacobianD,
   plant_functionJacA_column,
   plant_functionJacB_column,
   plant_functionJacC_column,
   plant_functionJacD_column,
   plant_linear_model_frame,
   plant_mayer,
   plant_lagrange,
   plant_pickUpBoundsForInputsInOptimization

};

void plant_setupDataStruc(DATA *data)
{
  assertStreamPrint(threadData,0!=data, "Error while initialize Data");
  data->callback = &plant_callback;
  data->modelData.modelName = "plant";
  data->modelData.modelFilePrefix = "plant";
  data->modelData.resultFileName = NULL;
  data->modelData.modelDir = "/home/ravi/DSTO/projects/Om/testing/learn";
  data->modelData.modelGUID = "{8c4e810f-3df3-4a00-8276-176fa3c9f9e0}";
  #ifdef OPENMODELICA_XML_FROM_FILE_AT_RUNTIME
  data->modelData.initXMLData = NULL;
  data->modelData.modelDataXml.infoXMLData = NULL;
  #else
  data->modelData.initXMLData =
  #include "plant_init.c"
  ;
  data->modelData.modelDataXml.infoXMLData =
  #include "plant_info.c"
  ;
  #endif
  
  data->modelData.nStates = 2;
  data->modelData.nVariablesReal = 2*2+0+0+0 + 0;
  data->modelData.nDiscreteReal = 0;
  data->modelData.nVariablesInteger = 0;
  data->modelData.nVariablesBoolean = 0;
  data->modelData.nVariablesString = 0;
  data->modelData.nParametersReal = 1;
  data->modelData.nParametersInteger = 0;
  data->modelData.nParametersBoolean = 0;
  data->modelData.nParametersString = 0;
  data->modelData.nInputVars = 0;
  data->modelData.nOutputVars = 0;
  
  data->modelData.nAliasReal = 0;
  data->modelData.nAliasInteger = 0;
  data->modelData.nAliasBoolean = 0;
  data->modelData.nAliasString = 0;
  
  data->modelData.nZeroCrossings = 0;
  data->modelData.nSamples = 0;
  data->modelData.nRelations = 0;
  data->modelData.nMathEvents = 0;
  data->modelData.nInitEquations = 0;
  data->modelData.nInitAlgorithms = 0;
  data->modelData.nInitResiduals = 0;    /* data->modelData.nInitEquations + data->modelData.nInitAlgorithms */
  data->modelData.nExtObjs = 0;
  setupModelInfoFunctions(1);
  data->modelData.modelDataXml.fileName = "plant_info.json";
  data->modelData.modelDataXml.modelInfoXmlLength = 0;
  data->modelData.modelDataXml.nFunctions = 0;
  data->modelData.modelDataXml.nProfileBlocks = 0;
  data->modelData.modelDataXml.nEquations = 7;
  data->modelData.nMixedSystems = 0;
  data->modelData.nLinearSystems = 0;
  data->modelData.nNonLinearSystems = 0;
  data->modelData.nStateSets = 0;
  data->modelData.nJacobians = 4;
  data->modelData.nOptimizeConstraints = 0;
  data->modelData.nOptimizeFinalConstraints = 0;
  
  data->modelData.nDelayExpressions = 0;
  
}

#ifdef __cplusplus
}
#endif

static int rml_execution_failed()
{
  fflush(NULL);
  fprintf(stderr, "Execution failed!\n");
  fflush(NULL);
  return 1;
}

#if defined(threadData)
#undef threadData
#endif
/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  int res;
  DATA simulation_data;
  MMC_INIT();omc_alloc_interface.init();
  {
    MMC_TRY_TOP()
  
    MMC_TRY_STACK()
  
    plant_setupDataStruc(&simulation_data);
    simulation_data.threadData = threadData;
    res = _main_SimulationRuntime(argc, argv, &simulation_data);
    
    MMC_ELSE()
    rml_execution_failed();
    fprintf(stderr, "Stack overflow detected and was not caught.\nSend us a bug report at https://trac.openmodelica.org/OpenModelica/newticket\n    Include the following trace:\n");
    printStacktraceMessages();
    fflush(NULL);
    return 1;
    MMC_CATCH_STACK()
    
    MMC_CATCH_TOP(return rml_execution_failed());
  }

  fflush(NULL);
  EXIT(res);
  return res;
}

